"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = [
    {
        title: "Mount Fuji",
        location: "Japan",
        googleMapsUrl: "https://goo.gl/maps/1DGM5WrWnATgkSNB8",
        startDate: "12 Jan, 2021",
        endDate: "24 Jan, 2021",
        description: "Mount Fuji is the tallest mountain in Japan, standing at 3,776 meters (12,380 feet). Mount Fuji is the single most popular tourist site in Japan, for both Japanese and foreign tourists.",
        imageUrl: "https://images.unsplash.com/photo-1525635569544-610f9540664a?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8bW91bnQlMjBmdWppfGVufDB8fDB8fHww",
    },
    {
        title: "Grand Canyon",
        location: "Arizona, USA",
        googleMapsUrl: "https://goo.gl/maps/1DGM5WrWnATgkSNB8",
        startDate: "12 Jan, 2021",
        endDate: "24 Jan, 2021",
        description: "The Grand Canyon is a steep-sided canyon carved by the Colorado River in Arizona, United States. The Grand Canyon is 277 miles (446 km) long, up to 18 miles (29 km) wide and attains a depth of over a mile (6,093 feet or 1,857 meters).",
        imageUrl: "https://images.unsplash.com/photo-1615551043360-33de8b5f410c?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Z3JhbmQlMjBjYW55b258ZW58MHx8MHx8fDA%3D",
    },
    {
        title: "Santorini",
        location: "Greece",
        googleMapsUrl: "https://goo.gl/maps/1DGM5WrWnATgkSNB8",
        startDate: "12 Jan, 2021",
        endDate: "24 Jan, 2021",
        description: "Santorini is one of the Cyclades islands in the Aegean Sea. It was devastated by a volcanic eruption in the 16th century BC, forever shaping its rugged landscape. The whitewashed, cubiform houses of its 2 principal towns, Fira and Oia, cling to cliffs above an underwater caldera (crater).",
        imageUrl: "https://plus.unsplash.com/premium_photo-1661963725253-c0632ab8782d?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8U2FudG9yaW5pfGVufDB8fDB8fHww",
    },
    {
        title: "Bora Bora",
        location: "French Polynesia",
        googleMapsUrl: "https://goo.gl/maps/1DGM5WrWnATgkSNB8",
        startDate: "12 Jan, 2021",
        endDate: "24 Jan, 2021",
        description: "Bora Bora is a small South Pacific island northwest of Tahiti in French Polynesia. Surrounded by sand-fringed motus (islets) and a turquoise lagoon protected by a coral reef, it’s known for its scuba diving. It's also a popular luxury resort destination where some guest bungalows are perched over the water on stilts.",
        imageUrl: "https://images.unsplash.com/photo-1580725869538-9b164c27c44f?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Ym9yYSUyMGJvcmF8ZW58MHx8MHx8fDA%3D",
    },
    {
        title: "Machu Picchu",
        location: "Peru",
        googleMapsUrl: "https://goo.gl/maps/1DGM5WrWnATgkSNB8",
        startDate: "12 Jan, 2021",
        endDate: "24 Jan, 2021",
        description: "Machu Picchu is an Incan citadel set high in the Andes Mountains in Peru, above the Urubamba River valley. Built in the 15th century and later abandoned, it’s renowned for its sophisticated dry-stone walls that fuse huge blocks without the use of mortar, intriguing buildings that play on astronomical alignments, and panoramic views.",
        imageUrl: "https://images.unsplash.com/photo-1587595431973-160d0d94add1?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8TWFjaHUlMjBQaWNjaHV8ZW58MHx8MHx8fDA%3D",
    },
    {
        title: "Petra",
        location: "Jordan",
        googleMapsUrl: "https://goo.gl/maps/1DGM5WrWnATgkSNB8",
        startDate: "12 Jan, 2021",
        endDate: "24 Jan, 2021",
        description: "Petra, the fabled “rose red city, half as old as time”, is a well known ancient Nabataean city in the south of Jordan. Due to its breathtaking grandeur and fabulous ruins, Petra was recognized as a World Heritage Site by UNESCO in 1985.",
        imageUrl: "https://images.unsplash.com/photo-1548786811-dd6e453ccca7?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8cGV0cmF8ZW58MHx8MHx8fDA%3D",
    },
    {
        title: "Great Wall of China",
        location: "China",
        googleMapsUrl: "https://goo.gl/maps/1DGM5WrWnATgkSNB8",
        startDate: "12 Jan, 2021",
        endDate: "24 Jan, 2021",
        description: "The Great Wall of China is a series of fortifications made of stone, brick, tamped earth, wood, and other materials, generally built along an east-to-west line across the historical northern borders of China to protect the Chinese states and empires against the raids and invasions of the various nomadic groups of the Eurasian Steppe.",
        imageUrl: "https://images.unsplash.com/photo-1608037521244-f1c6c7635194?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8R3JlYXQlMjBXYWxsJTIwb2YlMjBDaGluYXxlbnwwfHwwfHx8MA%3D%3D",
    },
    {
        title: "Taj Mahal",
        location: "India",
        googleMapsUrl: "https://goo.gl/maps/1DGM5WrWnATgkSNB8",
        startDate: "12 Jan, 2021",
        endDate: "24 Jan, 2021",
        description: "The Taj Mahal is an ivory-white marble mausoleum on the right bank of the Yamuna river in the Indian city of Agra. It was commissioned in 1632 by the Mughal emperor, Shah Jahan, to house the tomb of his favorite wife, Mumtaz Mahal.",
        imageUrl: "https://images.unsplash.com/photo-1587135941948-670b381f08ce?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8VGFqJTIwTWFoYWx8ZW58MHx8MHx8fDA%3D",
    },
    {
        title: "Pyramids of Giza",
        location: "Egypt",
        googleMapsUrl: "https://goo.gl/maps/1DGM5WrWnATgkSNB8",
        startDate: "12 Jan, 2021",
        endDate: "24 Jan, 2021",
        description: "The Pyramids of Giza consist of the Great Pyramid of Giza (also known as the Pyramid of Cheops or Khufu and constructed c. 2580 – c. 2560 BC), the somewhat smaller Pyramid of Khafre (or Chephren) a few hundred meters to the south-west, and the relatively modest size Pyramid of Menkaure (or Mykerinos) a few hundred meters further south-west.",
        imageUrl: "https://plus.unsplash.com/premium_photo-1661891622579-bee76e28c304?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8cHlyYW1pZHMlMjBvZiUyMGdpemF8ZW58MHx8MHx8fDA%3D",
    },
    {
        title: "Colosseum",
        location: "Italy",
        googleMapsUrl: "https://goo.gl/maps/1DGM5WrWnATgkSNB8",
        startDate: "12 Jan, 2021",
        endDate: "24 Jan, 2021",
        description: "The Colosseum is an oval amphitheater in the center of the city of Rome, Italy, just east of the Roman Forum. It is the largest ancient amphitheater ever built, and is still the largest standing amphitheater in the world today, despite its age.",
        imageUrl: "https://images.unsplash.com/photo-1552432552-06c0b0a94dda?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Y29sb3NzZXVtfGVufDB8fDB8fHww",
    },
    {
        title: "Eiffel Tower",
        location: "France",
        googleMapsUrl: "https://goo.gl/maps/1DGM5WrWnATgkSNB8",
        startDate: "12 Jan, 2021",
        endDate: "24 Jan, 2021",
        description: "The Eiffel Tower is a wrought-iron lattice tower on the Champ de Mars in Paris, France. It is named after the engineer Gustave Eiffel, whose company designed and built the tower.",
        imageUrl: "https://images.unsplash.com/photo-1431274172761-fca41d930114?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8ZWlmZmVsJTIwdG93ZXJ8ZW58MHx8MHx8fDA%3D",
    },
    {
        title: "Sydney Opera House",
        location: "Australia",
        googleMapsUrl: "https://goo.gl/maps/1DGM5WrWnATgkSNB8",
        startDate: "12 Jan, 2021",
        endDate: "24 Jan, 2021",
        description: "The Sydney Opera House is a multi-venue performing arts center at Sydney Harbour in Sydney, New South Wales, Australia. It is one of the 20th century's most famous and distinctive buildings.",
        imageUrl: "https://images.unsplash.com/photo-1523059623039-a9ed027e7fad?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8c3lkbmV5JTIwb3BlcmElMjBob3VzZXxlbnwwfHwwfHx8MA%3D%3D",
    },
    // {
    //   title: "Mesa Verde National Park",
    //   location: "Colorado, USA",
    //   googleMapsUrl: "https://goo.gl/maps/1DGM5WrWnATgkSNB8",
    //   startDate: "12 Jan, 2021",
    //   endDate: "24 Jan, 2021",
    //   description:
    //     "Mesa Verde National Park is an American national park and UNESCO World Heritage Site located in Montezuma County, Colorado. The park protects some of the best-preserved Ancestral Puebloan archaeological sites in the United States.",
    //   imageUrl:
    //     "https://images.unsplash.com/photo-1697425303371-23153f4d57f5?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fE1lc2ElMjBWZXJkZSUyME5hdGlvbmFsJTIwUGFya3xlbnwwfHwwfHx8MA%3D%3D",
    // },
];
